version: '3.9'

services:
  web:
    build: .
    command: php artisan serve --host=0.0.0.0 --port=8000
    ports:
      - 8000:8000
    depends_on:
      - database

  database:
    image: mysql:8
    # MySQL default-authentication-plugin
    # as of version 8, MySQL uses caching_sha2_password
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: laravel

    volumes:
      - 'mysql-data:/var/lib/mysql'

volumes:
  mysql-data:
